# Site settings
title: Melissa Paul 
email: meray1978@gmail.com
url: https://meray1978-beep.io/The-cyber-Defense-Blueprint
description: "Portfolio of cybersecurity work samples for a junior-level cyber security professional."
keywords: "cybersecurity, cyber, security, portfolio, tech"
skills: "Cybersecurity - Analyst - Ethical Hacker"
meta_author: Paul Melissa 

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: 

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: #0A192F
  primary-rgb: 10,25,47
  secondary: #00C8B4
  secondary-dark: #006964

# Footer settings
footer:
  copyright: Melissa Paul
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/melissa-ray-598093196
  - title: github
    url: https://github.com/meray1978-beep

# Email Address (make sure to include "mailto:" before your email!)
email:
  email-url: mailto:meray1978@gmail.om

# Postal address (add as many lines as necessary)
location:
  - line: Baton Rouge, Louisiana

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.
Cyber icons created by <a href="https://www.flaticon.com/free-icons/cyber-attack" title="cyber attack icons">Freepik - Flaticon</a>.'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
